MODEL:
  BACKBONE:
    NAME: "EVA2_VitDetLarge1024"
  WEIGHTS: "weights/WeVisionOne1.0-ViTL-Text.pt"
  SEM_SEG_HEAD:
    NAME: "MaskDINOHead"
    PIXEL_DECODER_NAME: "MaskDINOEarlyFusion"
    CONVS_DIM: 256
    IN_FEATURES: [ "res2", "res3", "res4", "res5" ]
    NUM_CLASSES: 133
  ENCODER:
    NUM_CLASSES: 133
    CONVS_DIM: 256
    MASK_DIM: 256
    NORM: "GN"
    IN_FEATURES: [ "res2", "res3", "res4", "res5" ]
    DEFORMABLE_TRANSFORMER_ENCODER_IN_FEATURES: [ "res2", "res3", "res4", "res5" ]
    COMMON_STRIDE: 4
    TRANSFORMER_ENC_LAYERS: 6
    TOTAL_NUM_FEATURE_LEVELS: 5
    NUM_FEATURE_LEVELS: 3
    FEATURE_ORDER: "low2high"
  DECODER:
    NHEADS: 8
    DROPOUT: 0.0
    DIM_FEEDFORWARD: 2048
  TEXT:
    MODEL_NAME: "../third_party/CLIP-ViT-L-14-laion2B-s32B-b82K"
    TOKEN_NAME: "../third_party/clip-vit-base-patch32"
  TRANSFORMER_DECODER:
    NAME: "MaskDINOLateFusion"
    HIDDEN_DIM: 256
    NUM_OBJECT_QUERIES: 900
    NHEADS: 8
    DROPOUT: 0.0
    DIM_FEEDFORWARD: 2048
    DEC_LAYERS: 9
    TOTAL_NUM_FEATURE_LEVELS: 5
    MASK_DIM: 256
    LEARN_TGT: True
